### ISSUE TITLE
do you still need the `libnet` username?

### ISSUE THREAD

**Issue by sam-github** [lmccord/try_git#1]
Hi there.

I'm one of the maintainers of the `libnet` package for packet crafting and injection. It has a small but important set of users, mostly network security tools.

I'd like to create a github organization that I can move the `libnet` project to make it easier to maintain and encourage collaboration from other people, and I'm trying to find a free organization name. Your username would be ideal, for obvious reasons :-).

If you are not using github.com/libnet anymore, would you be willing to donate it to our project?

Thank you,
Sam Roberts

**Comment by sam-github** [comment]
Hello?

**Comment by lmccord** [comment]
Sorry I was slow to respond.  I hardly ever check this email account.  (I do use github for a couple of projects.  I don’t need the name but I do need the account.)

If github can securely change the name on my account, that’s fine with me.  

(My name was Libby Netland which is why I had that name  )

 

Cc’ing to my other email account.

 

Libby

**Comment by lmccord** [comment]
So sorry!  I'm now seeing that you opened this a month ago!  
I'll see if I can rename my account this afternoon.

Libby

**Comment by sam-github** [comment]
Hi Libby, thanks for your response! Your personal email must have been
stripped, but I don't need it.

I don't want to steal your name, its your github name, you chose it in good
faith! But if you are willing to donate it, we'd appreciate it.

You can change your github account name, in the settings. If can find an
equally good new account name and want to give us libnet, thank you. If
not, we'll likely go with `libnet1`.

**Comment by lmccord** [comment]
Hi Sam,

libnet is available now, I think.
:)
Libby

**Comment by sam-github** [comment]
@lmccord Thank you so very much!
